# Generated by Django 4.0.1 on 2022-01-19 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('unit_symbol', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('install_date', models.DateField(default=datetime.date.today)),
                ('point', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='backend.point')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.FloatField()),
                ('station', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='backend.station')),
                ('type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='backend.datatype')),
            ],
            options={
                'verbose_name_plural': 'data',
            },
        ),
    ]
